baseURL = "https://nimishkhattar.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Nimsih Khattar"
theme = "dream"
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />Copyrights <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Attribution-Non-commercial use-Sharing in the same way 4.0 International <br /><br />(CC BY-NC-SA 4.0) <a href="https://www.pexels.com/zh-cn/" target="_blank">Pexels</a><br />© 2021 Nimish Khattar<br />Powered by Hugo with theme Dream.'
# after deploying
googleAnalytics = ""
disqusShortname = "nimishkhattar7"
utterancesRepo = ""

enableRobotsTXT = true

hasCJKLanguage = true

Paginate = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  dpage = "about"

  linkColor = "seagreen"

  # dark mode
  defaultDark = true
  backgroundDark = "#474747"
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true

  author = "Nimsih Khattar"
  description = "hey there I love physics"
  avatar = "/me/avatar.png"
  headerTitle = "Nimish Khattar"
  motto = "|| Competitive Programming || Problem solving  || Codeforces      ||<br>|| Software Developer      || Machine Learning || Cloud Computing ||<br>|| Engineer                ||<br>"
  maxTags = 5
  categoriesLimitInHeader = 6 

  # footerBottomText = ""

  # rss = true
  email = "NimishKhattar07@gmail.com"
  twitter = "KhattarNimish"

  linkedin = "nimish-khattar-537217179"
  github = "Nimishk07"
  stackoverflow = "13102926/nimish-khattar"

  siteStartYear = 2021

  favicon = "/fvicon.ico"

  highlightjs = true
  highlightjsExtraLanguages = ["clojure", "ocaml"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  reversePostAndAside = true
  collapseBySummary = true

  [params.advanced]
    customCSS = ["css/custom.css"]

  [params.experimental]
    jsDate = true
    jsDateFormat = "yyyy-MM-dd"
